### ISSUE TITLE
bat compatibility

### ISSUE THREAD

**Issue by black7375** [Riey/rust-pager#3]
The basic features work well. :+1: 

---

I tried `rp` after setting it as the default pager, but it is not compatible.
```shell
PAGER=rp
bat <file.name>
```

Pager is `less`
![image](https://user-images.githubusercontent.com/25581533/112712828-bf100180-8ec9-11eb-93df-61344d4d9747.png)

Pager is `rp`
![image](https://user-images.githubusercontent.com/25581533/112712834-cb945a00-8ec9-11eb-84ea-6097b426b40c.png)

Especially the problem is that the layout of the emulator is completely broken after running `bat`.
![image](https://user-images.githubusercontent.com/25581533/112712888-29c13d00-8eca-11eb-99bb-7fcf486ed571.png)

**Comment by Riey** [comment]
Now fixed

![20210327173045](https://user-images.githubusercontent.com/14910534/112715177-37a2ac80-8f22-11eb-9ede-d2f3cfc7e4c5.png)

**Comment by black7375** [comment]
I also checked.
